" Create the variable $RCPATH
let $RCPATH = "~/.vim/"

" Load additional configuration files
execute "source ".$RCPATH.fnameescape("settings/global-settings.vim")
execute "source ".$RCPATH.fnameescape("settings/plugins.vim")
execute "source ".$RCPATH.fnameescape("settings/mappings.vim")
execute "source ".$RCPATH.fnameescape("settings/customcolors.vim")
execute "source ".$RCPATH.fnameescape("settings/statusline.vim")
execute "source ".$RCPATH.fnameescape("settings/coc-config.vim")
