" Create the variable $RCPATH
let $RCPATH = "~/.vim/"

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

" Configure sets
set nocompatible
syntax on
filetype plugin indent on
set encoding=utf-8
set backspace=indent,eol,start
set mouse=a
set title
set number
set relativenumber
set belloff=all
set nobackup
set noswapfile
set confirm
set hidden
set splitbelow
set splitright
set undodir=~/.vim/undodir
set undofile
set scrolloff=2
" set cursorline
set autoindent
set smartindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smartcase
set incsearch
set ignorecase
set hls
set nowrap
set linebreak
set nolist
set listchars=tab:>-,space:.,trail:◀,eol:↲
" set fillchars=vert:│,fold:-,eob:~,lastline:@
set laststatus=2
set wildmenu
set wildmode=longest,full
" set wildoptions=pum   " pum with problems wsl2
" set complete+=kspell
" set completeopt=menuone,longest
" set shortmess+=c
set spelllang=en,pt_br
set nospell
set foldmethod=marker
set autoread

" Load plugins with vim-plug
call plug#begin($RCPATH.'/plugged')

Plug 'srcery-colors/srcery-vim'     " https://github.com/srcery-colors/srcery-terminal
Plug 'AxolotlC/Fox.vim'             " https://github.com/Pougher/Fox.vim

call plug#end()

" set background=dark   " with problems in wsl2
" colorscheme srcery

hi Normal guibg=NONE ctermbg=NONE
" CursorLine color: AliceBlue(246)
" hi CursorLine ctermbg=246
" hi CursorColumn ctermbg=246
hi Visual ctermbg=246
" hi Comment cterm=italic gui=italic

" Load additional configuration files
execute "source ".$RCPATH.fnameescape("statusbar.vim")
execute "source ".$RCPATH.fnameescape("mappings.vim")
