# Vi keys
set -g mode-keys vi

# Enable mouse
set -g mouse on

# Reload tmux config file with <Prefix> + r (inside a Tmux session)
bind r source-file ~/.tmux.conf \; display-message "Tmux config reloaded!"

# Switch panes with <Prefix> + h,j,k,l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# This config didn't work well in WSL (ESC and ALT are "meta" keys)
# bind -n M-j previous-window
# bind -n M-k next-window

# Open a new window, or split a window with the current path
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

# Better colors: render with 256 bits
# set -g default-terminal "xterm-256color"
set -g default-terminal "screen-256color"

# Plugin list
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Tmux Plugin Manager <Prefix> + i
run '~/.tmux/plugins/tpm/tpm'
